### ISSUE TITLE
HTTP Timeout error when trying to contact the molepro service

### ISSUE THREAD

**Issue by maximusunc** [TranslatorSRI/answer-appraiser#25]
https://github.com/TranslatorSRI/answer-appraiser/blob/a88c5a1eeefc849ccda6fbd9e4becc00922e0210/app/novelty/extr_smile_molpro_by_id.py#L25

**Comment by pg427** [comment]
Code Updated to account for this issue.

**Comment by maximusunc** [comment]
Fixed in #30
