### ISSUE TITLE
rdkit spews deprecation warnings

### ISSUE THREAD

**Issue by maximusunc** [TranslatorSRI/answer-appraiser#31]
DEPRECATION WARNING: please use MorganGenerator

**Comment by pg427** [comment]
Can I have an example of which json response this is caused by? Unfortunately, from the tests I've done I haven't encountered this issue.

**Comment by maximusunc** [comment]
I'm using the JSON response that was shared over Slack. PK: 7aa4575e-8f98-47fe-931a-85bd6178ed46

**Comment by pg427** [comment]
I am using an updated function (AllChem.GetMorganFingerprintAsBitVect) now to do the same. These should take care of any depreciation warnings going forward.

**Comment by maximusunc** [comment]
I'm still getting this warning with the new method. I think the issue is that you're on an old version of appraiser and need to pull and get updated. Since the beginning of last month, we've updated to python 3.12 and bumped all requirements versions. So I've been running with quite a bit newer versions than your local environment.

**Comment by maximusunc** [comment]
Fixed in #30
